version: '3'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: tournament
    ports:
      - 4532:4532

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080